version: '3'

networks:
  selenium-net:
    driver: bridge

services:
  tests:
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - selenium-net

  selenium-hub:
    image: FROM selenium/standalone-chrome-debug:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:3.8.1
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444