version: '3'

networks:
  selenium-net:
    driver: bridge

services:
  tests:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - selenium
    networks:
      - selenium-net

  selenium:
    image: selenium/standalone-firefox
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - selenium-net
    environment:
      - NODE_PORT=4444