version: '3'

networks:
  selenium-net:
    driver: bridge

# Создаем 2 образа в одной сети. В tests запускаются тесты, selenium нужен для создания среды выполнения тестов
services:
  tests:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - selenium
    networks:
      - selenium-net
    environment:
      - WD_URL=http://selenium:4444/wd/hub
      - WD_PLATFORM=linux
      - WD_BROWSER=chrome
      - WD_BROWSER_VERSION=88
      - GMAIL_USERNAME=aqa.engineer.test.alekseev.ms
      - GMAIL_PASSWORD=webcreateaccount1
      - GMAIL_URL=https://mail.google.com

  selenium:
    image: selenium/standalone-chrome:latest
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - selenium-net
    environment:
      - NODE_PORT=4444